{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.1.aar",
          "url": "navigation-runtime-2.4.1.aar",
          "size": 117238,
          "sha512": "b6caee3d9e90b587a0cf7a795a86e3796291feecf5b05db7082895f3867f8b3b5ff97f91be0ccb0d0f6c7fc17884788113c729b057e56f8449be198f46fb47bc",
          "sha256": "d77ea8d4abe767b95e9f066196d6f2a53da0bb905421a0886a648ee862efd3db",
          "sha1": "e52be5ee87b8de84d0458cd64f8a9818b79de8d5",
          "md5": "c19384832bcb03e4b7cd2e4a04fd067b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.4.1.aar",
          "url": "navigation-runtime-2.4.1.aar",
          "size": 117238,
          "sha512": "b6caee3d9e90b587a0cf7a795a86e3796291feecf5b05db7082895f3867f8b3b5ff97f91be0ccb0d0f6c7fc17884788113c729b057e56f8449be198f46fb47bc",
          "sha256": "d77ea8d4abe767b95e9f066196d6f2a53da0bb905421a0886a648ee862efd3db",
          "sha1": "e52be5ee87b8de84d0458cd64f8a9818b79de8d5",
          "md5": "c19384832bcb03e4b7cd2e4a04fd067b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.4.1-sources.jar",
          "url": "navigation-runtime-2.4.1-sources.jar",
          "size": 47025,
          "sha512": "a6f3f54294e741ede056579c2cf88bfc885356653f8ea4bd82817a774fd1d0192e98095b1b93e3e306df03e1526353ecd7018b3d2b66f5a16ceffdb4552d3c06",
          "sha256": "c98ab4a557d3670af51d348e1c445543360d73f13ff7657e2d6386615522b67a",
          "sha1": "0b407b0d69960fa7a1449c3171124b07a4cd8c59",
          "md5": "566a5c2e401e1ae19983686c024aabff"
        }
      ]
    }
  ]
}
